export const symbols = [
  // 📈 Indices (NSE)
  { type: "index", symbol: "NSE:NIFTY50" },
  { type: "index", symbol: "NSE:BANKNIFTY" },
  { type: "index", symbol: "NSE:NIFTYIT" },
  { type: "index", symbol: "NSE:NIFTYFIN" },
  { type: "index", symbol: "NSE:NIFTYAUTO" },

  // 🏦 Major Indian Stocks (NSE)
  { type: "stock", symbol: "NSE:RELIANCE" },
  { type: "stock", symbol: "NSE:TCS" },
  { type: "stock", symbol: "NSE:INFY" },
  { type: "stock", symbol: "NSE:HDFCBANK" },
  { type: "stock", symbol: "NSE:ICICIBANK" },
  { type: "stock", symbol: "NSE:LT" },
  { type: "stock", symbol: "NSE:SBIN" },
  { type: "stock", symbol: "NSE:ITC" },
  { type: "stock", symbol: "NSE:HINDUNILVR" },
  { type: "stock", symbol: "NSE:MARUTI" },
  { type: "stock", symbol: "NSE:AXISBANK" },
  { type: "stock", symbol: "NSE:KOTAKBANK" },
  { type: "stock", symbol: "NSE:BAJFINANCE" },
  { type: "stock", symbol: "NSE:BHARTIARTL" },
  { type: "stock", symbol: "NSE:SUNPHARMA" },
  { type: "stock", symbol: "NSE:TATAMOTORS" },
  { type: "stock", symbol: "NSE:TATASTEEL" },
  { type: "stock", symbol: "NSE:HCLTECH" },
  { type: "stock", symbol: "NSE:WIPRO" },
  { type: "stock", symbol: "NSE:ADANIENT" },
  { type: "stock", symbol: "NSE:POWERGRID" },
  { type: "stock", symbol: "NSE:ULTRACEMCO" },
  { type: "stock", symbol: "NSE:ONGC" },
  { type: "stock", symbol: "NSE:COALINDIA" },
  { type: "stock", symbol: "NSE:HDFCLIFE" },

  // 🌎 US Stocks (NASDAQ/NYSE)
  { type: "stock", symbol: "NASDAQ:TESLA" },
  { type: "stock", symbol: "NASDAQ:APPLE" },
  { type: "stock", symbol: "NASDAQ:NVIDIA" },

  // 💎 Cryptos (Finnhub requires "BINANCE:" prefix for Binance symbols)
  { type: "crypto", symbol: "BINANCE:BTCUSDT" },
  { type: "crypto", symbol: "BINANCE:ETHUSDT" },
  { type: "crypto", symbol: "BINANCE:SOLUSDT" },
  { type: "crypto", symbol: "BINANCE:XRPUSDT" },
  { type: "crypto", symbol: "BINANCE:ADAUSDT" },
  { type: "crypto", symbol: "BINANCE:DOGEUSDT" },
  { type: "crypto", symbol: "BINANCE:MATICUSDT" },
  { type: "crypto", symbol: "BINANCE:AVAXUSDT" },
  { type: "crypto", symbol: "BINANCE:DOTUSDT" },
  { type: "crypto", symbol: "BINANCE:LTCUSDT" },
];
